//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperKinoStudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int MovieId { get; set; }
        public int StudioId { get; set; }
        public string MovieName { get; set; }
        public int AreaId { get; set; }
        public Nullable<decimal> budgetFilm { get; set; }
    
        public virtual Studios Studios { get; set; }
        public virtual Studios Studios1 { get; set; }
    }
}
